feat: ФП13 реализация ТЗ. Добавлены контроллеры и сервисы для Item и …
MSmirnov2407/ShareIt pull request #1
Opened 2023-04-23 15:56 UTC by MSmirnov2407

…User

2023-04-23 22:46 UTC, NikolaiDem requested changes

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
В модели не нужны аннотации валидации ( @NotNull )

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Переопределять equals и hashCode нет необходимости. Лучше использовать отдельные аннотации из Lombok (Getter, Setter и т.д.)
В следующем спринте появится JPA в совокупности с переопределенными equals и hashCode могут быть следующие проблемы
https://habr.com/ru/companies/haulmont/articles/564682/

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  public class ItemController {
Все поля private

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.dtoToItem(newItemDto); //превращаем dto в объект
Задача контроллера - только маршрутизировать запрос. Поэтому всю бизнес логику лучше перенести в сервис, а в методе контроллера лишь вызвать метод сервиса.
Аналогично для остальных методов.

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Переопределять equals и hashCode нет необходимости. Лучше использовать отдельные аннотации из Lombok (Getter, Setter и т.д.)
В следующем спринте появится JPA в совокупности с переопределенными equals и hashCode могут быть следующие проблемы
https://habr.com/ru/companies/haulmont/articles/564682/

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
В модели не нужны аннотации валидации ( https://github.com/NotNull )

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
Переопределять equals и hashCode нет необходимости. Лучше использовать отдельные аннотации из Lombok (Getter, Setter и т.д.)
В следующем спринте появится JPA в совокупности с переопределенными equals и hashCode могут быть следующие проблемы
https://habr.com/ru/companies/haulmont/articles/564682/

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @NotBlank
В модели не нужны аннотации валидации ( https://github.com/NotNull )

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    UserService userService;
Все поля private

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.getAll().stream()
Задача контроллера - только маршрутизировать запрос. Поэтому всю бизнес логику лучше перенести в сервис, а в методе контроллера лишь вызвать метод сервиса.
Аналогично для остальных методов.

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Data
Переопределять equals и hashCode нет необходимости. Лучше использовать отдельные аннотации из Lombok (Getter, Setter и т.д.)
В следующем спринте появится JPA в совокупности с переопределенными equals и hashCode могут быть следующие проблемы
https://habr.com/ru/companies/haulmont/articles/564682/

2023-04-23 22:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +public class User {
В модели не нужны аннотации валидации

2023-04-25 19:34 UTC, MSmirnov2407 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.dtoToItem(newItemDto); //превращаем dto в объект
Николай, я поправил контроллеры, чтобы они не делали ничего, кроме вызова методов сервисов.
Но чувствую, что что-то не то, т.к. буквально сейчас прочитал вот [здесь](https://www.baeldung.com/java-dto-pattern) в п.5.2, что преобразование в DTO выполняется в контроллерном слое. Поправь, пожалуйста, если ошибаюсь)

2023-04-25 19:43 UTC, MSmirnov2407 commented
Николай, я поправил контроллеры, чтобы они не делали ничего, кроме вызова методов сервисов.
Но чувствую, что что-то не то, т.к. буквально сейчас прочитал вот [здесь](https://www.baeldung.com/java-dto-pattern) в п.5.2, что преобразование в DTO выполняется в контроллерном слое. Поправь, пожалуйста, если ошибаюсь)

2023-04-26 17:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Item item = ItemMapper.dtoToItem(newItemDto); //превращаем dto в объект
Михаил, отлично!
Статья скорее делает акцент на применении DTO как уменьшении количества обращений к сервису.
Здесь, вероятно, сделано в контроллере, чтобы показать, что пользователь получит все нужную информацию за один вызов контроллера.
В общем случае dto собирается из нескольких доменных объектов, что приводит к вызову в методе контроллера несколько методов сервиса, что размазывает логику сервиса между собой и контроллером. Поэтому, чтобы инкапсулировать бизнес-логику в одном месте, лучше делать маппинг в сервисе )

2023-04-26 17:43 UTC, NikolaiDem approved these changes

2023-04-26 18:21 UTC, merged